environment:
  global:
    CHANS_DEV: "-c pyviz/label/dev -c ioam -c bokeh -c conda-forge -c erdc -c defaults"
  matrix:
    - PY: "3.6"
      CONDA: "C:\\Miniconda36-x64"

install:
  - "SET PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - "conda install -y -c pyviz/label/dev pyct && doit ecosystem_setup"
  - "doit env_create --name=test --python=%PY%"
  - "activate test"
  - "doit develop_install %CHANS_DEV% -o recommended"
  - "doit env_capture"

build: off

test_script:
  - "earthsim download_data --path=examples"
  - "doit test_all"
