environment:
  global:
    CHANS_DEV: "-c pyviz/label/earthsim -c pyviz/label/dev -c erdc -c conda-forge"
  matrix:
    - PY: "3.6"
      CONDA: "C:\\Miniconda36-x64"

init:
  - cmd: set PATH=%CONDA%;%CONDA%\Scripts;%CONDA%\Library\bin;%PATH%
  - cmd: echo %path%

install:
  - "conda install -y -c pyviz pyctdev && doit ecosystem_setup"
  - "conda install -y conda<4.6"
  - "conda config --set always_yes True"
  - "doit env_create %CHANS_DEV% --name=earthsim --python=%PY%"
  - "activate earthsim"
  - "doit develop_install %CHANS_DEV% -o tests"
  - "doit env_capture"

build: off

test_script:
  - "earthsim fetch-data --path=examples"
  - "doit test_all"
