git:
  depth: 100

language: generic

env:
  global:
    - PYENV_VERSION=3.6
    - PKG_TEST_PYTHON="--test-python=py36"
    - CHANS_DEV="-c pyviz/label/earthsim -c pyviz/label/dev -c erdc -c conda-forge"
    - CHANS="-c pyviz"
    - MPLBACKEND="Agg"

cache:
  timeout: 300
  directories:
    - $HOME/miniconda

before_cache:
  - rm -rf $HOME/miniconda/pkgs
  - rm -rf $HOME/miniconda/conda-bld
  - rm -rf $HOME/miniconda/envs/*/conda-bld

notifications:
  email:
    on_failure: change # [always|never|change] default: always

stages:
  - test
  - name: user_install
    if: type = cron
  - name: doc
    if: branch = master AND type != pull_request

_osx_config: &_osx_config
  os: osx
  osx_image: xcode9.3
  env: PYENV_VERSION=3.6.4
  before_install:
    # set up python
    - eval "$(pyenv init -)"
    - pyenv install $PYENV_VERSION  
    # check the below still required
    # brew-installed geos interferes with cartopy?
    - brew uninstall --ignore-dependencies geos gdal postgis

jobs:
  include:
    ########## TEST USER INSTALL ##########
    - &default
      stage: test
      install:
        - pip install pyctdev && doit miniconda_install && pip uninstall -y doit pyctdev
        - export PATH="$HOME/miniconda/bin:$PATH" && hash -r
        - conda config --set always_yes True
        - conda install -c pyviz "pyctdev>=0.5" && doit ecosystem_setup
        - conda config --set path_conflict warn
        - doit env_create $CHANS_DEV --name=earthsim --python=$PYENV_VERSION
        - source activate earthsim
        - doit develop_install $CHANS_DEV -o tests
        - doit env_capture
      script:
        - earthsim fetch-data --path=examples
        - travis_wait 60 doit test_all
      after_failure:
        - sleep 10

    - <<: *default
      <<: *_osx_config

    ########## DOCS ##########
    - <<: *default
      stage: doc
      env: HV_DOC_HTML="true" DESC="docs"
      script:
        - conda install -c pyviz -c conda-forge nbsite=0.5.1 sphinx_ioam_theme
        - mkdir examples/assets
        - earthsim fetch-data --path=examples
        - nbsite generate-rst --org pyviz --project-name earthsim --offset 0 --skip '^.*Workflow.*$' --skip '^.*Sweep.*$'  --skip '^.*Batched.*$' --skip '^.Specifying.*$'
        - travis_wait 60 nbsite build --what=html --output=builtdocs
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: ./builtdocs
        fqdn: earthsim.pyviz.org
